require('dotenv').config();
const Product = require('./models/Product');
const connectDB = require('./conn/connection');

// Image filenames match exactly what's in frontend/src/assets/
// The frontend resolves these via the assetMap utility.
const products = [

  // ── RINGS ─────────────────────────────────────────────
  {
    name: "Symbol of forever ring",
    description: "A delicate ring symbolizing eternal love, crafted in adjustable size to fit all.",
    price: 400,
    stock: 5,
    sizes: ["Adjustable"],
    colors: [],
    images: ["Symbol of forever ring.jpeg"],
    category: "rings",
  },
  {
    name: "Emerald green stone ring",
    description: "Stunning emerald green stone set in a sleek band, available in sizes 7 and 8.",
    price: 480,
    stock: 6,
    sizes: ["7", "8"],
    colors: [],
    images: ["Emerald green stone ring.jpeg"],
    category: "rings",
  },
  {
    name: "Yin Yan ring",
    description: "Minimalist Yin Yang design ring, size 7, perfect for everyday wear.",
    price: 380,
    stock: 5,
    sizes: ["7"],
    colors: [],
    images: ["Yin Yan ring.jpeg"],
    category: "rings",
  },
  {
    name: "Spiral ring",
    description: "Elegant spiral design ring, adjustable to fit comfortably.",
    price: 250,
    stock: 3,
    sizes: ["Adjustable"],
    colors: [],
    images: ["Spiral ring.jpeg"],
    category: "rings",
  },
  {
    name: "Star moon ring",
    description: "Celestial star and moon ring available in sizes 7, 8, and 9.",
    price: 280,
    stock: 6,
    sizes: ["7", "8", "9"],
    colors: [],
    images: ["Star moon ring.jpeg"],
    category: "rings",
  },
  {
    name: "Black triangle",
    description: "Bold black triangle ring available in sizes 18 and 19.",
    price: 250,
    stock: 3,
    sizes: ["18", "19"],
    colors: [],
    images: ["Black triangle .jpeg"],
    category: "rings",
  },

  // ── HANDCUFFS ────────────────────────────────────────
  {
    name: "Cage style handcuff",
    description: "Edgy cage-style handcuff bracelet, one size fits all.",
    price: 950,
    stock: 2,
    sizes: [],
    colors: [],
    images: ["Cage style handcuff.jpeg"],
    category: "handcuff",
  },
  {
    name: "Emeraldgreen alternate stone handcuff",
    description: "Alternating emerald green stones set in a handcuff-style bracelet.",
    price: 600,
    stock: 3,
    sizes: [],
    colors: [],
    images: ["Emeraldgreen alternate stone .jpeg"],
    category: "handcuff",
  },
  {
    name: "Cartier nail style handcuff with ring",
    description: "Cartier-inspired nail style handcuff paired with a matching ring.",
    price: 1000,
    stock: 2,
    sizes: [],
    colors: [],
    images: ["Cartier nail style handcuff with ring .jpeg"],
    category: "handcuff",
  },
  {
    name: "Cartier style handcuff with ring",
    description: "Classic Cartier-style handcuff bracelet with a coordinating ring.",
    price: 1000,
    stock: 2,
    sizes: [],
    colors: [],
    images: ["Cartier style handcuff with ring .jpeg"],
    category: "handcuff",
  },
  {
    name: "White stone handcuff",
    description: "Elegant white stone handcuff bracelet, one size fits all.",
    price: 600,
    stock: 1,
    sizes: [],
    colors: [],
    images: ["White stone handcuff .jpeg"],
    category: "handcuff",
  },
  {
    name: "Beaded style handcuff",
    description: "Stylish beaded handcuff bracelet with a unique textured look.",
    price: 500,
    stock: 2,
    sizes: [],
    colors: [],
    images: ["Beaded style handcuff .jpeg"],
    category: "handcuff",
  },

  // ── HAND HARNESS ────────────────────────────────────
  {
    name: "Hand harness",
    description: "Trendy hand harness that drapes elegantly across the hand and wrist.",
    price: 480,
    stock: 3,
    sizes: [],
    colors: [],
    images: ["Hand harnes .jpeg"],
    category: "hand harness",
  },
  {
    name: "Double chain hand harness",
    description: "Double chain hand harness for a bold, layered look.",
    price: 500,
    stock: 3,
    sizes: [],
    colors: [],
    images: ["Double chain hand harness.jpeg"],
    category: "hand harness",
  },

  // ── EARRINGS ────────────────────────────────────────
  {
    name: "3 Earrings set",
    description: "A set of 3 complementary earrings for a versatile, mix-and-match style.",
    price: 300,
    stock: 1,
    sizes: [],
    colors: [],
    images: ["3 earrings set.jpeg"],
    category: "earrings",
  },
  {
    name: "3 Earrings set",
    description: "A set of 3 complementary earrings for a versatile, mix-and-match style.",
    price: 300,
    stock: 4,
    sizes: [],
    colors: [],
    images: [ "3 earrings set2.jpeg"],
    category: "earrings",
  },
  {
    name: "Sun style earrings",
    description: "Radiant sun-shaped earrings that add a bright touch to any outfit.",
    price: 380,
    stock: 5,
    sizes: [],
    colors: [],
    images: ["Sun style earrings .jpeg"],
    category: "earrings",
  },

  // ── BRACELETS ───────────────────────────────────────

  {
    name: "Seashell chain",
    description: "Ocean-inspired chain adorned with delicate seashell charms, perfect for a breezy, coastal aesthetic.",
    price: 400,
    stock: 3,
    sizes: [],
    colors: [],
    images: ["Seashell chain.jpeg"],
    category: "chains",
  },
  {
    name: "Cartier Style bracelet",
    description: "Sleek and sophisticated Cartier-inspired bracelet with a polished finish, a timeless staple for any wrist.",
    price: 350,
    stock: 6,
    sizes: [],
    colors: [],
    images: ["Cartier style bracelet .jpeg"],
    category: "bracelets",
  },
  {
    name: "Triple chain bracelet",
    description: "Layered triple chain bracelet for an effortlessly chic look.",
    price: 450,
    stock: 5,
    sizes: [],
    colors: [],
    images: ["Triple chain bracelet .jpeg"],
    category: "bracelets",
  },
  {
    name: "Single twisted bracelet unisex",
    description: "Unisex single twisted bracelet, sleek and minimal.",
    price: 350,
    stock: 5,
    sizes: [],
    colors: [],
    images: ["Single twisted bracelet unisex.jpeg"],
    category: "bracelets",
  },

  // ── CHAINS ─────────────────────────────────────────
  {
    name: "Ayat-ul-kursi pendant",
    description: "Beautiful Ayat-ul-Kursi pendant chain, a meaningful and elegant piece.",
    price: 400,
    stock: 2,
    sizes: [],
    colors: [],
    images: ["Ayat-ul-kursi pendant .jpeg"],
    category: "chains",
  },
  {
    name: "Starfish & seashell chain",
    description: "Ocean-inspired chain featuring starfish and seashell charms.",
    price: 500,
    stock: 2,
    sizes: [],
    colors: [],
    images: ["Starfish& seashell chain .jpeg"],
    category: "chains",
  },
  {
    name: "Colored stone chains",
    description: "Vibrant colored stone chain available in black, green, pink, and white.",
    price: 480,
    stock: 5,
    sizes: [],
    colors: ["black", "green", "pink", "white"],
    images: ["Colored stone chains.jpeg"],
    category: "chains",
  },
  {
    name: "Triple heart chain",
    description: "Romantic triple heart chain available in black and pink.",
    price: 480,
    stock: 6,
    sizes: [],
    colors: ["black", "pink"],
    images: ["Triple heart chain.jpeg"],
    category: "chains",
  },
  {
    name: "Bow set with unique chain",
    description: "Charming bow set paired with a uniquely designed chain.",
    price: 600,
    stock: 4,
    sizes: [],
    colors: [],
    images: ["Bow set with unique chain .jpeg"],
    category: "chains",
  },
  {
    name: "Silver chain & earrings set",
    description: "Matching silver chain and earrings set for a coordinated look.",
    price: 500,
    stock: 4,
    sizes: [],
    colors: [],
    images: ["Silver chain & earrings set.jpeg"],
    category: "chains",
  },
  {
    name: "Butterfly set",
    description: "Whimsical butterfly-themed chain set, delicate and feminine.",
    price: 500,
    stock: 5,
    sizes: [],
    colors: [],
    images: ["Butterfly set .jpeg"],
    category: "chains",
  },
  {
    name: "Single golden chains",
    description: "Classic single golden chain, timeless and versatile.",
    price: 250,
    stock: 9,
    sizes: [],
    colors: [],
    images: ["Single golden chains.jpeg"],
    category: "chains",
  },
  {
    name: "Single silver chains",
    description: "Sleek single silver chain, perfect for everyday wear.",
    price: 200,
    stock: 7,
    sizes: [],
    colors: [],
    images: ["Single silver chains.jpeg"],
    category: "chains",
  },
];

const seedDB = async () => {
  try {
    await connectDB();
    await Product.deleteMany({});
    await Product.insertMany(products);
    console.log(`✔ ${products.length} products seeded successfully!`);
    process.exit();
  } catch (err) {
    console.error(err);
    process.exit(1);
  }
};

seedDB();
